### ISSUE TITLE
TransGCN

### ISSUE THREAD

**Issue by caiyuefeng888** [gengchenmai/space2vec#3]
您好！打扰了，请问您方便给出您的《TransGCN:Coupling Transformation Assumptions with Graph
Convolutional Networks for Link Prediction》一文的代码，以供我个人学习之用吗?

**Comment by gengchenmai** [comment]
Hi,

Thanks for asking. I am not the first author of that paper. I will ask the author to see whether she want to publish the code of TransGCN.

Best,
Gengchen
